### ISSUE TITLE
45 degree “intention”

### ISSUE THREAD

**Issue by AnuthinWongsunkakon** [cadsondemak/Chakra-Petch#2]
Parin, Please make sure that the 45 degree “intention” can be applied correctly through out the whole set. Keep in mind that it does not have to be literally mathematic 45° . We only need to carry the optical that suggest the intention.

**Comment by parin-rungpattarathakun** [comment]
Noted with thanks. I will check and edit.

**Comment by AnuthinWongsunkakon** [comment]
Do you have the calculation of the head loop yet? I think it would be very helpful to test this before you go into this any deeper.

**Comment by parin-rungpattarathakun** [comment]
I already calculation and adjust the head loop. Most are tilted 45 degrees, but some have to adjust for the optical illusion.

**Comment by AnuthinWongsunkakon** [comment]
As the face get bolder I think you will run into a problem with the width. Wider width is allowed but please do not let it go too wide. I think it will change the original intention. Plus this is not a extended typeface. Please be very careful about the width.

**Comment by parin-rungpattarathakun** [comment]
Latin and Thai characters form 3 weight 
In Bold weight I try to condense width form original about 6 em
![chakra petchlast4extralight](https://user-images.githubusercontent.com/35288945/39764696-63622974-530a-11e8-9292-3b100f99e787.jpg)
![chakra petchregular](https://user-images.githubusercontent.com/35288945/39764699-6463e8a8-530a-11e8-817e-f358bf9f4109.jpg)
![chakra petchbold](https://user-images.githubusercontent.com/35288945/39764700-667bbcce-530a-11e8-8ded-b6da6a365023.jpg)
