### ISSUE TITLE
แบบของไม้ตรี

### ISSUE THREAD

**Issue by parin-rungpattarathakun** [cadsondemak/Chakra-Petch#3]
แบบของไม้ตรีเดิมนั้นผมมองว่าค่อนข้างมองออกยากว่าเป็นไม้ตรีครับ ซึ่งเราสามารถทำการปรับได้ไหมครับ
<img width="868" alt="screen shot 2561-03-14 at 11 43 10 am" src="https://user-images.githubusercontent.com/35288945/37383798-8f298f56-277d-11e8-9942-b95ce6f62f03.png">

**Comment by suppakit-** [comment]
ผมเห็นด้วยนะครับ ไม้ตรีถูกลดทอนเยอะเกินไปนิด ลองทำแบบมาเป็นทางเลือกเพื่อให้คนอื่นๆ ช่วยกันดูครับ ป.ล.ไม่โทใหญ่เกินไปนิดนึงครับ :)

**Comment by AnuthinWongsunkakon** [comment]
This is too extreme for Mei Tree. Could you please compare to the original. Keep in mind that you do not have to 100% strict with grid system. I also agree with @suppakit- the size of Mei Tor is too big especially when you compare with Karan. Would like to see this issues resolved.
