### ISSUE TITLE
แบบอักษรละติน และไทยที่ปรับแล้วครับ

### ISSUE THREAD

**Issue by parin-rungpattarathakun** [cadsondemak/Chakra-Petch#4]
แบบเดิม
![chakra petch](https://user-images.githubusercontent.com/35288945/37634761-710656ce-2c2a-11e8-98b5-a3e9d7655c88.jpg)

แบบที่ปรับใหม่
![chakra petchtest24](https://user-images.githubusercontent.com/35288945/37635672-acc27026-2c2f-11e8-877b-da04ea4c49f5.jpg)

1. ปรับขนาด และน้ำหนัก 400 ใหม่ 
2. ปรับ proportion ตัวละติน จากของเดิมที่ ตัวพิมพ์ใหญ่แคบไป และตัวพิมพ์เล็กกว้างไป แล้วปรับ propotion ภาษาไทยบางตัว
3. ในภาษาไทยเส้นเฉียง 45 องศาจะถูกใช้แทนที่ส่วนโค้งเท่านั้น แต่โครงสร้างก็ยังคงเป็นแบบปกติกว่า ส่วนในตัวละตินอย่าง A K V W X Y รวมถึงตัวพิมพ์เล็ก k v w x มีการพิเศษกว่าโครงสร้างปกติ ซึ่งทำให้ชุดตัวอักษรมีลักษณะพิเศษมากกว่าแบบตัวไทย จึงใช้หลักการเดียวกันกับภาษาไทยคือ นำเส้นเฉียง 45 องศาแทนที่ส่วนโค้งเท่านั้น
4. ปรับแบบ d t f p ให้อ่านง่ายขึ้น
5. ตัดปลายแหลมของกลุ่ม ผ ฝ พ ฟ

**Comment by AnuthinWongsunkakon** [comment]
ผมว่าทำได้ดีมากกว่าของเดิมอย่างเห็นได้ชัด ละติน น่าเชื่อมากขึ้นกว่าเดิม ทั้งในเรื่องของความกว้างที่ลงตัวมากขึ้น ผมอยากให้เพิ่ม LSB RSB มากกว่านี้อีกนิด เพื่อให้ทั้งเซทมันโปร่งขึ้นอีกนิดนึง ออกแนวโปรงมากกว่าของเดิม จะใช้งานได้ดีกว่าในเรื่องของการอ่าน 

ส่วนข้างล่างของ ฐ ไม่จำเป็นต้องเก็บแบบเดิมไว้เลย เพราะว่าถ้า ฏ ถูกต้องได้ ไม่มีเหตุเลยที่ ฐ จะเป็นแบบนี้เพียงเพื่อให้มันเก๋ อย่างนั้นหรือ? ผมว่าเฟสนี้มันเป็นเนื้อความที่ดีได้ มีแนวออกไปทางนั้น มันน่าจะแพรคติคอลกว่านี้ ดีกว่าที่พยายามออกแบบมากเกินไป
 
<img width="568" alt="screen shot 2018-03-20 at 12 02 09" src="https://user-images.githubusercontent.com/36420640/37636771-8ffe505c-2c36-11e8-8408-e7890c6508f4.png">

**Comment by parin-rungpattarathakun** [comment]
ขอบคุณมากเลยครับ เดียวผมจะปรับนะครับ

**Comment by AnuthinWongsunkakon** [comment]
You might want to cross check your Latin with @SmichSmanloh if you are uncertain. He will be more than happy to tip you off. 
<img width="849" alt="screen shot 2018-03-21 at 03 48 24" src="https://user-images.githubusercontent.com/36420640/37681977-ca655748-2cba-11e8-9447-5e2ebfd1b438.png">

<img width="756" alt="screen shot 2018-03-21 at 03 56 35" src="https://user-images.githubusercontent.com/36420640/37682356-f5e6bf1e-2cbb-11e8-8b80-b2f70f7eb300.png">

<img width="431" alt="screen shot 2018-03-21 at 04 01 31" src="https://user-images.githubusercontent.com/36420640/37682614-a6fb6d90-2cbc-11e8-8d90-4b2b7dd2d75a.png">
