### ISSUE TITLE
ขอคำปรึกษาเรื่อง overshoot สำหรับตัวไทย และละตินครับ

### ISSUE THREAD

**Issue by parin-rungpattarathakun** [cadsondemak/Chakra-Petch#5]
เนื่องจากแบบของตัว Chakraprtch ส่วนที่เป็นส่วนโค้งอย่างในตัว o e หรือ c จะเป็นเส้นนอนที่มีความยาวพอสมควร ผมเลยอยากปรึกษาว่าผมควรทำ Overshoot ให้กับส่วนโค้งเหล่านี้ไหม
แบบที่ 1 ยังไม่ได้มีการทำ overshoot <img width="1226" alt="screen shot 2561-03-30 at 3 34 57 pm" src="https://user-images.githubusercontent.com/35288945/38131406-265608f4-3431-11e8-861b-ebc62a3a2310.png">
แบบที่ 2 ทำ overshoot เพิ่มมาทั้งบนและล่างอย่างละ 6 em ครับ
<img width="1359" alt="screen shot 2561-03-30 at 4 01 27 pm" src="https://user-images.githubusercontent.com/35288945/38132137-fe59ff10-3433-11e8-8e3f-1ecc0198418a.png">

ส่วนในภาษาไทยส่วนหัวกลมผมทดเพิ่มมา 8 em ครับ
แบบที่ 1 ยังไม่ได้มีการทำ overshoot 
<img width="891" alt="screen shot 2561-03-30 at 3 53 41 pm" src="https://user-images.githubusercontent.com/35288945/38131809-9eb84590-3432-11e8-8357-2abaa00267e8.png">

แบบที่ 2 ทำ overshoot เพิ่มมาทั้งบนและล่างอย่างละ 8
<img width="867" alt="screen shot 2561-03-30 at 3 38 05 pm" src="https://user-images.githubusercontent.com/35288945/38132170-2176567e-3434-11e8-96eb-3aa7da4d5fae.png">

**Comment by suppakit-** [comment]
ในความเห็นผมคิดว่า ไม่จำเป็นต้องทดก็ได้สำหรับตัวอักษรที่มีเส้นแนวนอนค่อนข้างยาว เช่น c e o s  ฯ แต่อาจทดกับตัว a b d m n t ฯ และสำหรับอักษรไทย ผมคิดว่าทดgCrktหัวตัวอักษรก็เพียงพอครับ :D

**Comment by AnuthinWongsunkakon** [comment]
ผมก็เห็นด้วยกับพี่เช่นะครับ พอมีเส้นนอนให้พักแล้วแบบนี้ อาจจะลืม overshoot ไปก็ได้นะ ดูแบบมันไม่ค่อยเรียกร้องให้มีสักเท่าไหร แล้วมีในกรณีนี้อาจจะทำให้การแสดงผลเวลา Hinting มันยากไปอีกดวยซ้ำเพราะที่ overshoot ไปมันไม่ใช่เส้นโค้ง แต่แค่เป็นเส้นนอนที่ represent เส้นโค้งเท่านั้น
