### ISSUE TITLE
Width of Bold weight

### ISSUE THREAD

**Issue by parin-rungpattarathakun** [cadsondemak/Chakra-Petch#8]
Old bold weight is wide than regular and Extralight. I try to decrease width by 6 em. I think it can't narrow than this because Thai characters have many part inside. But I'm not sure, Please advice me.

Extralight
![chakra petchlast4extralight](https://user-images.githubusercontent.com/35288945/40038913-7ccaf196-583e-11e8-94ca-bd59ab868a46.jpg)

Regular
![chakra petchregular](https://user-images.githubusercontent.com/35288945/40039029-e524f67e-583e-11e8-8a46-f93ec4cff516.jpg)

New Bold
![chakra petchbold](https://user-images.githubusercontent.com/35288945/40038891-6e4a8ad2-583e-11e8-8598-4c5943d9db6a.jpg)

Old Bold 
![oldbold](https://user-images.githubusercontent.com/35288945/40039035-ed6a07e8-583e-11e8-8704-54e0632ecb9b.jpg)

**Comment by suppakit-** [comment]
หลังจากปรับ Proportion ของตัว Bold ใหม่ ให้แคบลงนิดนึงแล้ว ดูน่าเชื่อขึ้นครับ

**Comment by SmichSmanloh** [comment]
ระบบของ terminal เช่น a c s C G J จะพบว่าเมื่อโค้งเกินครึ่งหนึ่งจะมีโค้งปิดจนจบ แต่ถ้าโค้งไม่ถึงครึ่งจะปล่อยปลายจบเป็นเส้นตรงไว้ เช่น j t r ในส่วนของ tail ตัว g และ y ถ้าดูจากระบบที่วางไว้ของชุดตัวอักษร น่าจะโค้งปิดแบบตัว a c s C G J หรือเปล่าครับ?
<img width="1068" alt="screen shot 2561-05-22 at 20 11 26" src="https://user-images.githubusercontent.com/7007652/40364541-d13df12e-5dfc-11e8-8e75-50a64f8ede7d.png">

**Comment by SmichSmanloh** [comment]
ตัว ย ผมลองเติมบาร์ข้างใน พบว่าเพิ่ม legibility ให้สูงขึ้น เมื่อใช้งานในขนาดเล็กครับ
<img width="1000" alt="screen shot 2561-05-22 at 20 14 34" src="https://user-images.githubusercontent.com/7007652/40364613-f9d17b10-5dfc-11e8-9c5c-33250d53e771.png">

**Comment by suppakit-** [comment]
เห็นด้วยกับประเด็นเติมบาร์ด้านใน ย ครับ ช่วยให้ชัดเจนขึ้นในขนาดเล็ก

**Comment by parin-rungpattarathakun** [comment]
ขอบคุณครับผม @suppakit-  @SmichSmanloh ผมจะทำการปรับตามคอมเมนต์นะครับ
